Add moonphase command
SniperNoob95/NASABot pull request #2
Opened 2022-05-02 00:35 UTC by kjsmita6

NASA_moonphase - Displays the current phase of the moon

2022-05-03 00:31 UTC, kjsmita6 commented
Converted to slash command, should be ready to merge.

2022-05-04 05:24 UTC, SniperNoob95 requested changes
Please remove the double tabs and match the existing indention levels.

Rename Moonphase.java -> MoonPhaseSlashCommand.java

2022-05-04 11:44 UTC, kjsmita6 reviewed
Fixed spacing. Leaving Moonphase.java as that is the normal (non-slash command) version of the command to match the current style (other commands have a slash version and a non-slash version).

2022-05-05 00:44 UTC, SniperNoob95 approved these changes

2022-05-05 00:44 UTC, merged